import Head from "next/head";
import Image from "next/image";
import ArticleComp from "../component/articleComp";

export default function Home() {
  return (
    <div className="px-8 mt-10 lg:px-0 lg:mt-0 lg:flex lg:items-center lg:justify-center lg:h-screen">
      <Head>
        <title>Article Preview Componet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <ArticleComp />
    </div>
  );
}
